parameters:
#    tafrika_user.example.class: Tafrika\UserBundle\Example

services:
    tafrika_user.registration.form.type:
        class: Tafrika\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: tafrika_user_registration }

    Gravatar.twig.extension:
        class: Tafrika\UserBundle\Twig\GravatarExtension
        tags:
            -  { name: twig.extension }
