<?php

namespace Tafrika\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getUserList($userPerPage, $page){
        if($page<1){
            throw new \InvalidArgumentException('L\'argument $page ne peut être inférieur à 1 (valeur : "'.$page.'").');
        }
        $query = $this->createQueryBuilder('u')
            ->getQuery();

        $query->setFirstResult( ($page-1)*$userPerPage );
        $query->setMaxResults($userPerPage);
        return new Paginator($query);
    }
}
