tafrika_admin:
    resource: "@TafrikaAdminBundle/Resources/config/routing.yml"
    prefix:   /

tafrika_post:
    resource: "@TafrikaPostBundle/Resources/config/routing.yml"
    prefix:   /

tafrika_user:
    resource: "@TafrikaUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /oauth/login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google