post_show:
    path: /show/{post_slug}
    defaults: { _controller: TafrikaPostBundle:Post:showPost }

post_delete:
    path: /delete/{post_id}
    defaults: { _controller: TafrikaPostBundle:Post:deletePost}
    requirements:
        post_id: \d+

post_load:
    path: /load
    defaults: { _controller: TafrikaPostBundle:Post:loadPosts }

signal_nsfw:
    path: /nsfw_post
    defaults: { _controller: TafrikaPostBundle:General:signalNSFW }
    methods: [POST]

signal_porn:
    path: /porn_post
    defaults: { _controller: TafrikaPostBundle:General:signalPorn }
    methods: [POST]

vote_up:
   path: /vote_up
   defaults: { _controller: TafrikaPostBundle:Post:VoteUp }
   methods: [POST]

vote_down:
   path: /vote_down
   defaults: { _controller: TafrikaPostBundle:Post:VoteDown }
   methods: [POST]