post_show:
    path: show/{post_id}
    defaults: { _controller: TafrikaPostBundle:Post:showPost }
    requirements:
        post_id: \d+

signal_nsfw:
    path: /nsfw_post
    defaults: { _controller: TafrikaPostBundle:General:signalNSFW }
    methods: [POST]

signal_porn:
    path: /porn_post
    defaults: { _controller: TafrikaPostBundle:General:signalPorn }
    methods: [POST]
