tafrika_index:
    path: /
    defaults: { _controller: TafrikaPostBundle:General:loadHotPosts }

tafrika_freshk:
    path: /freshk
    defaults: { _controller: TafrikaPostBundle:General:index }

Tafrika_status:
    resource: "@TafrikaPostBundle/Resources/config/routing/status.yml"
    prefix: /status

Tafrika_video:
    resource: "@TafrikaPostBundle/Resources/config/routing/video.yml"
    prefix: /video

Tafrika_image:
    resource: "@TafrikaPostBundle/Resources/config/routing/image.yml"
    prefix: /image

Tafrika_comment:
    resource: "@TafrikaPostBundle/Resources/config/routing/comment.yml"
    prefix: /comment

Tafrika_post:
    resource: "@TafrikaPostBundle/Resources/config/routing/post.yml"
    prefix: /post

load_followed_posts:
    path: /followedPost
    defaults: { _controller: TafrikaPostBundle:General:loadFollowedUserPost }

nsfw_change:
    path: /change_nsfw
    defaults: { _controller: TafrikaPostBundle:General:changeNSFWState }