tafrika_index:
    path: /{page}
    defaults: { _controller: TafrikaPostBundle:General:Index, page: 1 }
    requirements:
        page: \d+

status_add:
    path: /status/add
    defaults: { _controller: TafrikaPostBundle:Status:addStatus }

status_show:
    path: /status/{status_id}
    defaults: { _controller: TafrikaPostBundle:Status:showStatus }
    requirements:
        status_id: \d+

status_edit:
    path: /status/{status_id}/edit
    defaults: { _controller: TafrikaPostBundle:Status:editStatus }
    requirements:
        status_id: \d+

video_add:
    path: /video/add
    defaults: { _controller: TafrikaPostBundle:Video:addVideo }

video_show:
    path: /video/{video_id}
    defaults: { _controller: TafrikaPostBundle:Video:showVideo }
    requirements:
        video_id: \d+

video_edit:
    path: /video/{video_id}
    defaults: { _controller: TafrikaPostBundle:Video:editVideo }
    requirements:
        video_id: \d+

image_add:
    path: /image/add
    defaults: { _controller: TafrikaPostBundle:Image:addImage }

image_show:
    path: /image/{image_id}
    defaults: { _controller: TafrikaPostBundle:Image:showImage }
    requirements:
        image_id: \d+

image_edit:
    path: /image/{image_id}/edit
    defaults: { _controller: TafrikaPostBundle:Image:editImage }
    requirements:
        image_id: \d+

comment_add:
    path: /status/{status_id}
    defaults: { _controller: TafrikaPostBundle:Comment:addComment }
    requirements:
            status_id: \d+