tafrika_index:
    path: /{page}
    defaults: { _controller: TafrikaPostBundle:General:Index, page: 1 }
    requirements:
        page: \d+

Tafrika_status:
    resource: "@TafrikaPostBundle/Resources/config/routing/status.yml"
    prefix: /status

Tafrika_video:
    resource: "@TafrikaPostBundle/Resources/config/routing/video.yml"
    prefix: /video

Tafrika_image:
    resource: "@TafrikaPostBundle/Resources/config/routing/image.yml"
    prefix: /image

Tafrika_comment:
    resource: "@TafrikaPostBundle/Resources/config/routing/comment.yml"
    prefix: /comment

Tafrika_post:
    resource: "@TafrikaPostBundle/Resources/config/routing/post.yml"
    prefix: /post

nsfw_change:
    path: /change_nsfw
    defaults: { _controller: TafrikaPostBundle:General:changeNSFWState }

vote_up_status:
    path: /status/{status_id}/voteUp
    defaults: { _controller: TafrikaPostBundle:Status:voteUpStatus }
    options:
            expose: true
    requirements:
            status_id: \d+

vote_down_status:
    path: /status/{status_id}/voteDown
    defaults: { _controller: TafrikaPostBundle:Status:voteDownStatus }
    options:
                expose: true
    requirements:
            status_id: \d+

vote_up_image:
    path: /image/{image_id}/voteUp
    defaults: { _controller: TafrikaPostBundle:Image:voteUpImage }
    options:
                expose: true
    requirements:
            status_id: \d+

vote_down_image:
    path: /image/{image_id}/voteDown
    defaults: { _controller: TafrikaPostBundle:Image:voteDownImage }
    options:
                expose: true
    requirements:
            status_id: \d+

vote_up_video:
    path: /video/{video_id}/voteUp
    defaults: { _controller: TafrikaPostBundle:Video:voteUpVideo }
    options:
                expose: true
    requirements:
            status_id: \d+

vote_down_video:
    path: /video/{video_id}/voteDown
    defaults: { _controller: TafrikaPostBundle:Video:voteDownVideo }
    options:
                expose: true
    requirements:
            status_id: \d+
