<?php

namespace Tafrika\PostBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findFresh($postPerPage, $page, $nsfw){
        if($page<1){
            throw new \InvalidArgumentException("L'argument page ne peut pas être inférieur à 1");
        }

        $query = $this->createQueryBuilder('p');
        if($nsfw==1) {
            $query->where('p.NSFW = :nsfw')
                ->setParameter('nsfw', $nsfw);
        }
        $query->orderBy('p.createdAt','DESC');
        $query->getQuery();
        $query->setFirstResult( ($page - 1)* $postPerPage);
        $query->setMaxResults($postPerPage);
        return new Paginator($query);
    }
}
